---
- name: playbook1
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  vars_files: 
    - vars/users.yml

  tasks:
    - name: Ensure users are created
      user:
        name: "{{ item.value.username }}"
        password: "{{ item.password | string | password_hash('sha512') }}"
        comment: "{{ item.value.email }}"
        update_password: allways
      with_dict: "{{ users }}"
             